### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by auisdhf878tyc807asdhfiunkm** [words/powerthesaurus-api#7]
This doesn't seem to work anymore -- it just returns an empty array no matter what I do.

**Comment by dmahfouda** [comment]
I'm also experiencing this issue—

**Comment by wooorm** [comment]
They seem to change all the time: https://github.com/words/powerthesaurus-api/issues?q=is%3Aissue+is%3Aclosed

PRs welcome to help out with a more solid solution

**Comment by wooorm** [comment]
@zeke should we deprecate this perhaps? Their stuff keeps changing... 😩

**Comment by zeke** [comment]
@deebah or @dmahfouda this module breaks whenever the website changes its HTML structure. The last time this happened it was a one-line change because of an updated CSS class name. Are you interested in attempting to work on a fix?

**Comment by ryanwbass** [comment]
@zeke Hey, I am currently looking for a good thesaurus api. Based on the website this looks pretty promising and am feeling adventurous enough to contribute to something like this. Digging through the code to understand and some debugging it looks like I would have to update:
`done(null, $.selectAll('main .k3_b', tree).map(each))`
as $.selectAll is returning [].
So Im assuming that '.k3_b' element had its name changed or something along those lines. 

What element from the site were you guys originally selecting with that identifier?

**Comment by zeke** [comment]
Hi @ryanwbass thanks for jumping in. I don't remember the historical DOM structure of the site off-hand. The best way for you to proceed would be to open the PowerThesaurus website in your browser, do a search, then see the selectors in the browser's web inspector. From there you can extrapolate and figure out what selectors would need to be changed here in this package. Hope that helps.

**Comment by adnanshahri** [comment]
@ryanwbass 
Have you had the chance to work on this, or did you find a better API?

**Comment by ghost** [comment]
@zeke 
Hi, is the issue still persistent?

@ryanwbass 
Have you had the chance to work on this, or did you find a better API than Power Thesaurus?
